channels:
- conda-forge
dependencies:
- python=3.10.1
- pip<=21.2.4
- pip:
  - mlflow==3.4.0
  - cloudpickle==3.1.1
  - numpy==2.2.6
  - pandas==2.3.2
  - psutil==7.1.0
  - pyarrow==21.0.0
  - scikit-learn==1.7.2
  - scipy==1.15.3
name: mlflow-env
